/**
 * B-roll Indexer Module — Phase 3
 *
 * Scans a B-roll library directory on SSD, catalogs video clips into
 * a SQLite database with metadata and descriptions per clip.
 *
 * Schema:
 *   clips(id, file_path, filename, duration, width, height, fps,
 *         file_size, description, tags, indexed_at, file_hash)
 *
 * Descriptions are generated by analyzing clip filenames, directory
 * structure, and optionally keyframe extraction + AI description.
 * For v1, descriptions come from filename parsing + directory context.
 */

import Database from "better-sqlite3";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { readdir, stat, mkdir } from "node:fs/promises";
import { join, dirname, extname, basename, relative } from "node:path";
import { createHash } from "node:crypto";
import { readFileSync, mkdirSync, openSync, readSync, closeSync } from "node:fs";

const execFileAsync = promisify(execFile);

const VIDEO_EXTENSIONS = new Set([
  ".mp4", ".mov", ".avi", ".mkv", ".webm", ".m4v", ".mxf", ".prores",
]);

const DB_SCHEMA = `
  CREATE TABLE IF NOT EXISTS clips (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    file_path TEXT UNIQUE NOT NULL,
    filename TEXT NOT NULL,
    directory TEXT NOT NULL,
    duration REAL,
    width INTEGER,
    height INTEGER,
    fps REAL,
    file_size INTEGER,
    description TEXT,
    tags TEXT,
    indexed_at TEXT NOT NULL,
    file_hash TEXT
  );

  CREATE INDEX IF NOT EXISTS idx_clips_file_path ON clips(file_path);
  CREATE INDEX IF NOT EXISTS idx_clips_tags ON clips(tags);
  CREATE INDEX IF NOT EXISTS idx_clips_file_hash ON clips(file_hash);
`;

/**
 * Open or create the B-roll index database.
 *
 * @param {string} dbPath - Path to the SQLite database file
 * @returns {import("better-sqlite3").Database}
 */
export function openDatabase(dbPath) {
  mkdirSync(dirname(dbPath), { recursive: true });
  const db = new Database(dbPath);
  db.pragma("journal_mode = WAL");
  db.exec(DB_SCHEMA);
  return db;
}

/**
 * Scan a directory recursively for video files.
 *
 * @param {string} dirPath - Root directory to scan
 * @returns {AsyncGenerator<string>} Yields absolute paths to video files
 */
export async function* scanDirectory(dirPath, _visitedInodes = new Set()) {
  const entries = await readdir(dirPath, { withFileTypes: true });

  // Track visited directories by inode to detect symlink loops
  const dirStats = await stat(dirPath).catch(() => null);
  if (dirStats) {
    const inodeKey = `${dirStats.dev}:${dirStats.ino}`;
    if (_visitedInodes.has(inodeKey)) return; // Symlink loop detected
    _visitedInodes.add(inodeKey);
  }

  for (const entry of entries) {
    const fullPath = join(dirPath, entry.name);

    // Skip hidden entries and node_modules
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue;

    // Resolve symlinks by checking the actual file type
    const fileStats = await stat(fullPath).catch(() => null);
    if (!fileStats) continue;

    if (fileStats.isDirectory()) {
      yield* scanDirectory(fullPath, _visitedInodes);
    } else if (fileStats.isFile()) {
      const ext = extname(entry.name).toLowerCase();
      if (VIDEO_EXTENSIONS.has(ext)) {
        yield fullPath;
      }
    }
  }
}

/**
 * Get video metadata using ffprobe.
 *
 * @param {string} filePath - Path to the video file
 * @returns {Promise<{duration: number, width: number, height: number, fps: number}>}
 */
export async function getClipMetadata(filePath) {
  const { stdout } = await execFileAsync("ffprobe", [
    "-v", "quiet",
    "-print_format", "json",
    "-show_format",
    "-show_streams",
    filePath,
  ]);

  const data = JSON.parse(stdout);
  const videoStream = data.streams?.find((s) => s.codec_type === "video");

  return {
    duration: parseFloat(data.format?.duration || "0"),
    width: videoStream ? parseInt(videoStream.width) : 0,
    height: videoStream ? parseInt(videoStream.height) : 0,
    fps: videoStream ? parseFrameRate(videoStream.r_frame_rate) : 0,
    fileSize: parseInt(data.format?.size || "0"),
  };
}

/**
 * Parse FFmpeg frame rate string (e.g., "30000/1001" → 29.97)
 */
function parseFrameRate(rateStr) {
  if (!rateStr) return 0;
  const parts = rateStr.split("/");
  if (parts.length === 2) {
    const num = parseInt(parts[0]);
    const den = parseInt(parts[1]);
    return den > 0 ? num / den : 0;
  }
  return parseFloat(rateStr) || 0;
}

/**
 * Generate a content hash for a file (first 1MB + file size).
 * This is fast enough for large video files while still detecting changes.
 *
 * @param {string} filePath
 * @param {number} fileSize
 * @returns {string} hex hash
 */
export function computeFileHash(filePath, fileSize) {
  const hash = createHash("sha256");
  // Read only first 1MB for fast hashing of large video files
  const CHUNK = 1024 * 1024;
  const buf = Buffer.allocUnsafe(Math.min(CHUNK, fileSize || CHUNK));
  const fd = openSync(filePath, "r");
  try {
    const bytesRead = readSync(fd, buf, 0, buf.length, 0);
    hash.update(buf.slice(0, bytesRead));
  } finally {
    closeSync(fd);
  }
  hash.update(String(fileSize));
  return hash.digest("hex");
}

/**
 * Generate a description from the filename and directory structure.
 *
 * Parses common B-roll naming conventions:
 * - "city-skyline-night.mp4" → "city skyline night"
 * - "medical/surgery-room-panning.mov" → "medical: surgery room panning"
 * - "B_ROLL_HOSPITAL_EXTERIOR_001.mp4" → "hospital exterior"
 *
 * @param {string} filePath - Full path to clip
 * @param {string} libraryRoot - Root of the B-roll library
 * @returns {string} Human-readable description
 */
export function generateDescription(filePath, libraryRoot) {
  const rel = relative(libraryRoot, filePath);
  const parts = rel.split("/");
  const filename = parts.pop();

  // Clean up filename: remove extension, numbers, common prefixes
  let name = basename(filename, extname(filename));
  name = name
    .replace(/^[Bb][-_]?[Rr][Oo][Ll][Ll][-_]?/i, "") // Remove "B-Roll" prefix
    .replace(/[-_]+/g, " ")                              // Dashes/underscores to spaces
    .replace(/\b\d{2,4}\b/g, "")                        // Remove sequence numbers
    .replace(/\s+/g, " ")                                // Collapse whitespace
    .trim()
    .toLowerCase();

  // Add directory context (e.g., "medical/surgery" → "medical: surgery ...")
  const dirContext = parts
    .filter(p => !p.startsWith("."))
    .map(p => p.replace(/[-_]+/g, " ").toLowerCase().trim())
    .filter(Boolean);

  if (dirContext.length > 0) {
    return `${dirContext.join(" / ")}: ${name}`.trim();
  }

  return name || basename(filename);
}

/**
 * Extract tags from a description string.
 * Splits description into individual words as tags.
 *
 * @param {string} description
 * @returns {string} Comma-separated tags
 */
export function extractTags(description) {
  const words = description
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .split(/\s+/)
    .filter(w => w.length > 2)       // Skip very short words
    .filter((w, i, arr) => arr.indexOf(w) === i);  // Deduplicate

  return words.join(",");
}

/**
 * Index a single clip into the database.
 *
 * @param {import("better-sqlite3").Database} db
 * @param {string} filePath - Absolute path to the clip
 * @param {string} libraryRoot - Root of the B-roll library
 * @param {object} options
 * @returns {Promise<{action: "inserted"|"skipped"|"updated", filePath: string}>}
 */
export async function indexClip(db, filePath, libraryRoot, options = {}) {
  // Check if already indexed
  const existing = db.prepare("SELECT id, file_hash FROM clips WHERE file_path = ?").get(filePath);

  // Get file stats
  const fileStats = await stat(filePath);
  const fileSize = fileStats.size;

  // Compute hash for change detection
  const fileHash = computeFileHash(filePath, fileSize);

  if (existing && existing.file_hash === fileHash) {
    return { action: "skipped", filePath };
  }

  // Get metadata from ffprobe
  const metadata = await getClipMetadata(filePath);

  // Generate description
  const description = options.description || generateDescription(filePath, libraryRoot);
  const tags = extractTags(description);

  const now = new Date().toISOString();

  if (existing) {
    // Update existing record (file changed)
    db.prepare(`
      UPDATE clips SET
        duration = ?, width = ?, height = ?, fps = ?, file_size = ?,
        description = ?, tags = ?, indexed_at = ?, file_hash = ?
      WHERE id = ?
    `).run(
      metadata.duration, metadata.width, metadata.height, metadata.fps, fileSize,
      description, tags, now, fileHash, existing.id
    );
    return { action: "updated", filePath };
  }

  // Insert new record
  const dir = relative(libraryRoot, filePath).split("/").slice(0, -1).join("/") || ".";
  db.prepare(`
    INSERT INTO clips (file_path, filename, directory, duration, width, height, fps,
                       file_size, description, tags, indexed_at, file_hash)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `).run(
    filePath, basename(filePath), dir,
    metadata.duration, metadata.width, metadata.height, metadata.fps, fileSize,
    description, tags, now, fileHash
  );
  return { action: "inserted", filePath };
}

/**
 * Index an entire B-roll library directory.
 *
 * Scans for video files, checks each against the database,
 * and indexes new/changed clips.
 *
 * @param {string} libraryPath - Root directory of B-roll library
 * @param {string} dbPath - Path to SQLite database file
 * @param {object} options
 * @returns {Promise<{total: number, inserted: number, updated: number, skipped: number, errors: number}>}
 */
export async function indexLibrary(libraryPath, dbPath, options = {}) {
  const { onProgress } = options;

  await mkdir(join(dbPath, ".."), { recursive: true }).catch(() => {});

  const db = openDatabase(dbPath);
  const stats = { total: 0, inserted: 0, updated: 0, skipped: 0, errors: 0 };

  try {
    for await (const filePath of scanDirectory(libraryPath)) {
      stats.total++;
      try {
        const result = await indexClip(db, filePath, libraryPath);
        stats[result.action]++;
        if (onProgress) onProgress(stats, result);
      } catch (err) {
        stats.errors++;
        if (onProgress) onProgress(stats, { action: "error", filePath, error: err.message });
      }
    }
  } finally {
    db.close();
  }

  return stats;
}

/**
 * Query the B-roll index for clips matching search terms.
 *
 * @param {string} dbPath - Path to SQLite database
 * @param {string} query - Search terms (space-separated)
 * @returns {Array} Matching clips
 */
export function searchClips(dbPath, query) {
  const db = openDatabase(dbPath);
  try {
    const terms = (query || "").toLowerCase().split(/\s+/).filter(Boolean);
    if (terms.length === 0) {
      return db.prepare("SELECT * FROM clips ORDER BY filename").all();
    }

    // Escape LIKE wildcards in user input (%, _)
    const escapeLike = (s) => s.replace(/[%_]/g, "\\$&");

    // Match clips where description or tags contain ALL search terms
    const conditions = terms.map(() => "(description LIKE ? ESCAPE '\\' OR tags LIKE ? ESCAPE '\\')").join(" AND ");
    const params = terms.flatMap(t => {
      const escaped = `%${escapeLike(t)}%`;
      return [escaped, escaped];
    });

    return db.prepare(`SELECT * FROM clips WHERE ${conditions} ORDER BY filename`).all(params);
  } finally {
    db.close();
  }
}

/**
 * Get summary stats from the index.
 *
 * @param {string} dbPath
 * @returns {{totalClips: number, totalDuration: number, directories: number}}
 */
export function getIndexStats(dbPath) {
  const db = openDatabase(dbPath);
  try {
    const row = db.prepare(`
      SELECT COUNT(*) as totalClips,
             COALESCE(SUM(duration), 0) as totalDuration,
             COUNT(DISTINCT directory) as directories
      FROM clips
    `).get();
    return row;
  } finally {
    db.close();
  }
}

// CLI entry point
if (process.argv[1]?.endsWith("broll-indexer.js") && process.argv[2]) {
  const command = process.argv[2];

  if (command === "index") {
    const libraryPath = process.argv[3];
    const dbPath = process.argv[4] || "data/broll-index.db";

    if (!libraryPath) {
      console.error("Usage: broll-indexer.js index <library-path> [db-path]");
      process.exit(1);
    }

    console.log(`[broll-indexer] Indexing B-roll library: ${libraryPath}`);
    console.log(`[broll-indexer] Database: ${dbPath}\n`);

    indexLibrary(libraryPath, dbPath, {
      onProgress: (stats, result) => {
        if (result.action === "inserted") {
          console.log(`  + ${basename(result.filePath)}`);
        } else if (result.action === "updated") {
          console.log(`  ~ ${basename(result.filePath)}`);
        } else if (result.action === "error") {
          console.log(`  ! ${basename(result.filePath)}: ${result.error}`);
        }
      },
    }).then((stats) => {
      console.log(`\n[broll-indexer] Done: ${stats.total} clips scanned`);
      console.log(`  Inserted: ${stats.inserted}`);
      console.log(`  Updated:  ${stats.updated}`);
      console.log(`  Skipped:  ${stats.skipped}`);
      console.log(`  Errors:   ${stats.errors}`);
    }).catch((err) => {
      console.error("[broll-indexer] Error:", err.message);
      process.exit(1);
    });
  } else if (command === "search") {
    const query = process.argv.slice(3).join(" ");
    const dbPath = "data/broll-index.db";

    const results = searchClips(dbPath, query);
    console.log(`[broll-indexer] ${results.length} clips matching "${query}":`);
    for (const clip of results) {
      console.log(`  ${clip.filename} — ${clip.description} (${clip.duration?.toFixed(1)}s)`);
    }
  } else if (command === "stats") {
    const dbPath = process.argv[3] || "data/broll-index.db";
    const stats = getIndexStats(dbPath);
    console.log(`[broll-indexer] Index stats:`);
    console.log(`  Clips: ${stats.totalClips}`);
    console.log(`  Total duration: ${(stats.totalDuration / 60).toFixed(1)} min`);
    console.log(`  Directories: ${stats.directories}`);
  }
}
